version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdatabase
      MYSQL_PASSWORD: root
    ports:
      - "3316:3306"
